package com.takawo.fan.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.takawo.fan.db.FandbContent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FANDB_CONTENT.
*/
public class FandbContentDao extends AbstractDao<FandbContent, Void> {

    public static final String TABLENAME = "FANDB_CONTENT";

    /**
     * Properties of entity FandbContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property GameId = new Property(0, long.class, "gameId", true, "GAME_ID");
        public final static Property ContentId = new Property(1, long.class, "contentId", true, "CONTENT_ID");
        public final static Property Path = new Property(2, String.class, "path", false, "PATH");
        public final static Property Comment = new Property(3, String.class, "comment", false, "COMMENT");
    };


    public FandbContentDao(DaoConfig config) {
        super(config);
    }
    
    public FandbContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FANDB_CONTENT' (" + //
                "'GAME_ID' INTEGER PRIMARY KEY NOT NULL ," + // 0: gameId
                "'CONTENT_ID' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 1: contentId
                "'PATH' TEXT," + // 2: path
                "'COMMENT' TEXT);"); // 3: comment
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FANDB_CONTENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FandbContent entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getGameId());
        stmt.bindLong(2, entity.getContentId());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(3, path);
        }
 
        String comment = entity.getComment();
        if (comment != null) {
            stmt.bindString(4, comment);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public FandbContent readEntity(Cursor cursor, int offset) {
        FandbContent entity = new FandbContent( //
            cursor.getLong(offset + 0), // gameId
            cursor.getLong(offset + 1), // contentId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // path
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // comment
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FandbContent entity, int offset) {
        entity.setGameId(cursor.getLong(offset + 0));
        entity.setContentId(cursor.getLong(offset + 1));
        entity.setPath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setComment(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(FandbContent entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(FandbContent entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
