package com.takawo.fan.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FANDB_IMAGE.
 */
public class FandbImage {

    private long playerId;
    private long gameId;
    private Long id;
    private String path;
    private String title;
    private String comment;

    public FandbImage() {
    }

    public FandbImage(Long id) {
        this.id = id;
    }

    public FandbImage(long playerId, long gameId, Long id, String path, String title, String comment) {
        this.playerId = playerId;
        this.gameId = gameId;
        this.id = id;
        this.path = path;
        this.title = title;
        this.comment = comment;
    }

    public long getPlayerId() {
        return playerId;
    }

    public void setPlayerId(long playerId) {
        this.playerId = playerId;
    }

    public long getGameId() {
        return gameId;
    }

    public void setGameId(long gameId) {
        this.gameId = gameId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
