package com.takawo.fan.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FANDB_PLAYER.
 */
public class FandbPlayer {

    private long playerId;
    /** Not-null value. */
    private String playerName;
    /** Not-null value. */
    private String gameEvent;
    private long resultType;
    private String categoryId;
    private String playerColor;
    private String playerImagePath;
    private String playerComment;

    public FandbPlayer() {
    }

    public FandbPlayer(long playerId) {
        this.playerId = playerId;
    }

    public FandbPlayer(long playerId, String playerName, String gameEvent, long resultType, String categoryId, String playerColor, String playerImagePath, String playerComment) {
        this.playerId = playerId;
        this.playerName = playerName;
        this.gameEvent = gameEvent;
        this.resultType = resultType;
        this.categoryId = categoryId;
        this.playerColor = playerColor;
        this.playerImagePath = playerImagePath;
        this.playerComment = playerComment;
    }

    public long getPlayerId() {
        return playerId;
    }

    public void setPlayerId(long playerId) {
        this.playerId = playerId;
    }

    /** Not-null value. */
    public String getPlayerName() {
        return playerName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /** Not-null value. */
    public String getGameEvent() {
        return gameEvent;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGameEvent(String gameEvent) {
        this.gameEvent = gameEvent;
    }

    public long getResultType() {
        return resultType;
    }

    public void setResultType(long resultType) {
        this.resultType = resultType;
    }

    public String getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public String getPlayerColor() {
        return playerColor;
    }

    public void setPlayerColor(String playerColor) {
        this.playerColor = playerColor;
    }

    public String getPlayerImagePath() {
        return playerImagePath;
    }

    public void setPlayerImagePath(String playerImagePath) {
        this.playerImagePath = playerImagePath;
    }

    public String getPlayerComment() {
        return playerComment;
    }

    public void setPlayerComment(String playerComment) {
        this.playerComment = playerComment;
    }

}
