package com.takawo.fan.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FANDB_GAME.
 */
public class FandbGame {

    private long playerId;
    private long gameId;
    private long gameType;
    private String gameCategory;
    private String place;
    private String weather;
    private String temperature;
    /** Not-null value. */
    private java.util.Date gameDay;
    private String startTime;
    private String endTime;
    private String opposition;
    private String result;
    private String resultScore;
    private String resultTime;
    private String comment;

    public FandbGame() {
    }

    public FandbGame(long playerId, long gameId) {
        this.playerId = playerId;
        this.gameId = gameId;
    }

    public FandbGame(long playerId, long gameId, long gameType, String gameCategory, String place, String weather, String temperature, java.util.Date gameDay, String startTime, String endTime, String opposition, String result, String resultScore, String resultTime, String comment) {
        this.playerId = playerId;
        this.gameId = gameId;
        this.gameType = gameType;
        this.gameCategory = gameCategory;
        this.place = place;
        this.weather = weather;
        this.temperature = temperature;
        this.gameDay = gameDay;
        this.startTime = startTime;
        this.endTime = endTime;
        this.opposition = opposition;
        this.result = result;
        this.resultScore = resultScore;
        this.resultTime = resultTime;
        this.comment = comment;
    }

    public long getPlayerId() {
        return playerId;
    }

    public void setPlayerId(long playerId) {
        this.playerId = playerId;
    }

    public long getGameId() {
        return gameId;
    }

    public void setGameId(long gameId) {
        this.gameId = gameId;
    }

    public long getGameType() {
        return gameType;
    }

    public void setGameType(long gameType) {
        this.gameType = gameType;
    }

    public String getGameCategory() {
        return gameCategory;
    }

    public void setGameCategory(String gameCategory) {
        this.gameCategory = gameCategory;
    }

    public String getPlace() {
        return place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public String getWeather() {
        return weather;
    }

    public void setWeather(String weather) {
        this.weather = weather;
    }

    public String getTemperature() {
        return temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    /** Not-null value. */
    public java.util.Date getGameDay() {
        return gameDay;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGameDay(java.util.Date gameDay) {
        this.gameDay = gameDay;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getOpposition() {
        return opposition;
    }

    public void setOpposition(String opposition) {
        this.opposition = opposition;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getResultScore() {
        return resultScore;
    }

    public void setResultScore(String resultScore) {
        this.resultScore = resultScore;
    }

    public String getResultTime() {
        return resultTime;
    }

    public void setResultTime(String resultTime) {
        this.resultTime = resultTime;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
