package com.takawo.fan.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FANDB_CONTENT.
 */
public class FandbContent {

    private long gameId;
    private long contentId;
    private String path;
    private String comment;

    public FandbContent() {
    }

    public FandbContent(long gameId, long contentId) {
        this.gameId = gameId;
        this.contentId = contentId;
    }

    public FandbContent(long gameId, long contentId, String path, String comment) {
        this.gameId = gameId;
        this.contentId = contentId;
        this.path = path;
        this.comment = comment;
    }

    public long getGameId() {
        return gameId;
    }

    public void setGameId(long gameId) {
        this.gameId = gameId;
    }

    public long getContentId() {
        return contentId;
    }

    public void setContentId(long contentId) {
        this.contentId = contentId;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
